### ISSUE TITLE
Can this work with ESP8266?

### ISSUE THREAD

**Issue by bilogic** [53l3cu5/ESP32_LD2450#4]
Hi! Great work!

I wasn't able to get it to work with ESP8266 even though I changed the board etc. 
When connecting to check logs, HA cannot connect to the port 6053.

I did notice that UART had a debug section, is it required?

**Comment by 53l3cu5** [comment]
Hello, I have not personally worked on the ESP 8266. So I can't answer your question precisely. 

What I can tell you though is that the ld2450 requires a lot of computing power. And sometimes even with  ESP32, we are at the limit of its computing capacity.

**Comment by bilogic** [comment]
thanks, I will switch to an ESP32.
