### ISSUE TITLE
zone.h

### ISSUE THREAD

**Issue by gravino1973** [53l3cu5/ESP32_LD2450#7]
hi,
at first i want to say that you did a great job very nice thank you 
i want to install more than one radar in my house, must i create for each sensor a new zone.h and also give a different name of just one is enough for al the radar

kindly regards 

Gravino

**Comment by mauritsivs** [comment]
what is the zone.h file used for and where do i place it?

**Comment by nliviu** [comment]
@gravino1973 Only one `zone.h` is necessary.

@mauritsivs You can place it in the same folder as the `yaml` file, or in any other place you want and adjust the path [here](https://github.com/53l3cu5/ESP32_LD2450/blob/0305d9d9790766eb99e47b63bf87b3485a198d2f/esp-presence-2450.yaml#L37)

**Comment by gravino1973** [comment]
@nliviu thank you very much for your help

**Comment by 53l3cu5** [comment]
nliviu is absolutely right
thank you very much for answering so quickly
