### ISSUE TITLE
position mirrored

### ISSUE THREAD

**Issue by mauritsivs** [53l3cu5/ESP32_LD2450#8]
The code works perfectly in ESPhome. Only it seems that the X-axis is mirrored compared to what you see on the HLK radar tool. 
When you move to the right, in the HLK radar tool you see the target moving to the right and the Angle goes to negative numbers. In Home assistant, the angle is also displaying correctly negative numbers, But in the Plotly graph the movement is going to the left.
looks like the simple solution is to switch the x-axis range from (-4000,4000) to (4000,-4000) etc...

**Comment by sylvainbizeau** [comment]
This is not an error or a bug. It's just a difference in perspective. I've already been told about this problem in the past. But the sensor documentation defines the axes as I wrote. I won't correct this point but you are free to do so in your own version

**Comment by 53l3cu5** [comment]
This is not an error or a bug. It's just a difference in perspective. I've already been told about this problem in the past. But the sensor documentation defines the axes as I wrote. I won't correct this point but you are free to do so in your own version
